export * from './modules/home'
export * from './modules/popuplist'
export * from './modules/img'
export * from './modules/detail'
export * from './modules/home'
export * from './modules/carlist'
export * from './modules/color'
export * from './modules/base'
export * from './modules/share';
export * from './modules/pic';